#!/usr/bin/env bash
#using the while loop to display multiple things on multiple lines
i=1
while [ $i -le 10 ];
do
i=$(( i+1 ))
if [[ $i = 5 ]];
then echo "bad luck";
elif [[ $i = 9 ]];
then echo "good luck";
     else echo "Best School";
fi
done
